Lesson 12 oauth
arthurkulchenko/qna_think pull request #13
Opened 2016-09-29 18:44 UTC by arthurkulchenko

2016-09-30 16:02 UTC, vkurennov requested changes
У тебя очень страдает качество кода, просто катострофически. Старайся использовать более простые конструкции, не усложняй. Код должен бытль понятным и легкочитаемым. Ну и уж совсем очевидных глупостей вроде одного и того же выражени в условии и в его теле нельзя допускать. 

В общем, давай отрефактори это насколько сможешь, иначе, дальше мы не пойдем.

2016-09-30 16:02 UTC, vkurennov commented on app/controllers/omniauth_callbacks/confirmations_controller.rb
> +class OmniauthCallbacks::ConfirmationsController < Devise::ConfirmationsController
Ну и зачем этот контроллер?

2016-09-30 16:02 UTC, vkurennov commented on app/controllers/omniauth_callbacks/omniauth_callbacks_controller.rb
> +    # render json: request.env["omniauth.auth"]
А не многовато комментариев ты оставляешь? Лучше делай коммиты чаще, тогда можно вернуться к предыдущим версиям и посмотреть их.

2016-09-30 16:02 UTC, vkurennov commented on app/controllers/omniauth_callbacks/passwords_controller.rb
> +class OmniauthCallbacks::PasswordsController < Devise::PasswordsController
Удали все, что тебе не нужно. Хватит мусорить в репозитории, этот код потом будут потенциальные работодатели смотреть и им это не понравится также, как и мне.

2016-09-30 16:02 UTC, vkurennov commented on app/controllers/set_emails_controller.rb
> +class SetEmailsController < ApplicationController
И что это за ресурс такой SetEmail? Про REST-архитекутру слышал? В реальном проекте за такой контроллер руки оторвут. Уж прости зя прямоту.
Подумай: какой ресурс мы тут меняем? И можно ли переложить то, что ты хочешь, на CRUD-операции с этим ресурсом? А может, лучше использовать существующий ресурс?

2016-09-30 16:02 UTC, vkurennov commented on app/controllers/set_emails_controller.rb
> +    @token = SecureRandom.base64(18)
Всю это логику нужно вынести в модели, т.к. бизнес-логика не ответственность контроллера

2016-09-30 16:02 UTC, vkurennov commented on app/controllers/set_emails_controller.rb
> +      if @user_by_email
Совмести условия

2016-09-30 16:02 UTC, vkurennov commented on app/controllers/set_emails_controller.rb
> +        EmailConfirmationMailer.please_confirm_email(@user, @token).deliver_now
В обоих ветках условия одно и то же, зачем тогда выносить это в условия?

2016-09-30 16:02 UTC, vkurennov commented on app/controllers/set_emails_controller.rb
> +      EmailConfirmationMailer.please_confirm_email(@user, user.token).deliver_now
И опять дублирование

2016-09-30 16:02 UTC, vkurennov commented on app/models/user.rb
> +    user_by_email = self
Зачем?

2016-09-30 16:02 UTC, vkurennov commented on app/models/user.rb
> +    [:authorizations].each do |association|
Перебирать массив из одного элемента? Зачем?

2016-09-30 16:02 UTC, vkurennov commented on app/models/user.rb
> +      association.name.to_s.classify.constantize.where(user_id: younger_user.id).each do |class_instance|
А просто написать `Authoriztion.where(...)` или еще лучше `user.authorizations` не пробовал?

2016-09-30 16:02 UTC, vkurennov commented on app/models/user.rb
> +      association.name.to_s.classify.constantize.where(user_id: younger_user.id).each do |class_instance|
Зачем вообще перебирать все авторизации у юзера?

2016-09-30 16:02 UTC, vkurennov commented on app/models/user.rb
> +        association.name.to_s.classify.constantize.create!(new_attr.merge(user: elder_user, email_confirmation_token: token))
А просто создать авторизацию с нужными параметрами нельзя?

2016-09-30 16:02 UTC, vkurennov commented on app/models/user.rb
> +    if User.find_by_auth(req)
Ничего не смущает в этом коде? Например, двойное выполнение каждого метода?

2016-09-30 16:13 UTC, arthurkulchenko commented on app/models/user.rb
> +    [:authorizations].each do |association|
Если мы зашли через фб, подтвердили email, и в следующий раз мы заходим через твиттер и нам снова нужно подтвердить email, когда мы попытаемся поддтвердить ящик, то возникает ошибка существующего email. Для решения этой проблемы я решил сливать двух юзеров в одного.

2016-09-30 16:16 UTC, arthurkulchenko commented on app/models/user.rb
> +      association.name.to_s.classify.constantize.where(user_id: younger_user.id).each do |class_instance|
это замена `User.reflect_on_all_associations(:has_many)`,  для пересоздания всех имеющихся у пользователя объектов.

2016-09-30 16:18 UTC, arthurkulchenko commented on app/models/user.rb
> +    if User.find_by_auth(req)
Смущает... только вот не додумал как лучше сделать.

2016-09-30 16:27 UTC, arthurkulchenko commented on app/controllers/set_emails_controller.rb
> +class SetEmailsController < ApplicationController
Пугающая категоричность) если переложить CRUD на @user то тогда столкнемся со проблемой допуска к обновлению пользователя, если мы ограничим его через аутентификацию, что в последующем как я полагаю нам потребуется для управления пользователем

2016-10-04 18:15 UTC, vkurennov requested changes
Стало лучше, код чище, понятнее. Правда, потом все же увлекся и наворотил каких-то ненужных методов класса, но с этим уже можно работать и можно рефакторить

2016-10-04 18:15 UTC, vkurennov commented on app/controllers/authorizations_controller.rb
> +    @auth.update!(is_confirmed: true, confirmation_token: nil)
Тут не нужен update!, т.к. в этом случае будет выброшено исключение и пользователь увидит 500 ошибку. Лучше сделать условие, и если объект не сохранился, написать юзеру, что произошла ошибка.

2016-10-04 18:15 UTC, vkurennov commented on app/helpers/authorizations_helper.rb
> +module AuthorizationsHelper
Удаляй пустые файлы

2016-10-04 18:15 UTC, vkurennov commented on app/models/user.rb
> +    if authorization
Избавься от elsif, слишком длинная конструкция получается. Сделай как в скринкасте: `return authorization.user if authorization`, тогда не будет elsif

2016-10-04 18:15 UTC, vkurennov commented on app/models/user.rb
> +      token_and_password_generating
Эта строка в обоих ветках, поэтому ее нужно вынести ДО условия

2016-10-04 18:15 UTC, vkurennov commented on app/models/user.rb
> +  class << self
А зачем тебе методы класса? Сделай приватными инстанс-методами

2016-10-04 18:15 UTC, vkurennov commented on app/models/user.rb
> +      token_and_password_generating
Это же метод класса, а вызываешь его как инстанс-метод. Как это работает?

2016-10-04 18:15 UTC, vkurennov commented on app/models/user.rb
> +        @r_email = true
А тут еще и инстанс-переменные уровня класса. И где они используются?

2016-10-04 18:15 UTC, vkurennov commented on app/models/user.rb
> +  def merge_this(user)
Я что-то не улавливаю смысл этого метода. Что ты тут пытаешься сделать? Копируешь авторизации от одного юзера другому? Зачем? (не говорю, что это плохо, просто хочу понять цель этого действия)
Ну и проще это сделать, заменив ассоциацию у авторизаций с одного юзера на другого.

2016-10-04 19:01 UTC, arthurkulchenko commented on app/models/user.rb
> +  def merge_this(user)
Заходим через фб -> создается пользователь с email и создается авторизация
Заходим тем же человеком через твиттер -> создается авторизация и фейковый юзер

И человек то один а юзеров уже 2, как-то неправильно.
Все равно прежде чем запустить пользователя мы просим подтвердить почту(что наверное не лучшая практика) и в этой связи пользователь вводит свою почту, которая уже к этому времени есть в бд блягодаря первой авторизации(через фб) и тут получается что нужно этих пользователей объеденить. И на этот раз мы объеденяем только авторизации, в отличии от первой редакции, где объеденялись все дочерние объекты, что наверное затратно по ресурсам... хотя количество пользователей для объеденения, я думаю, может достигать максимус 7, больше уже наверное не есть хороший тон - поддерживать вход через 15 разных рп

2016-10-04 19:15 UTC, arthurkulchenko commented on app/models/user.rb
> +  def merge_this(user)
вот)

2016-10-04 19:17 UTC, arthurkulchenko commented on app/models/user.rb
> +        @r_email = true
Это случай, когда мы заходим первый раз, если заходим через фб, то создается пользователь с нормальной почтой, если заходим через твит то создается костыльная почта, на первый этап до введения реальной.

2016-10-04 19:26 UTC, arthurkulchenko commented on app/models/user.rb
> +    if authorization
но elsif нужен чтобы не вкладвать в else еще один if else, ведь метод работает по принципу

1. Ищем пользователя по авторизации, если не находим то...
2. Ищем пользователя по почте, если не находим, то
3. Создаем нового пользователя

я не представляю как избежать этого спагетти условия

2016-10-04 19:27 UTC, arthurkulchenko commented on app/models/user.rb
> +    if authorization
но elsif нужен чтобы не вкладвать в else еще один if else, ведь метод работает по принципу
1. Ищем пользователя по авторизации, если не находим то...
2. Ищем пользователя по почте, если не находим, то
3. Создаем нового пользователя

я не представляю как избежать этого спагетти условия

2016-10-04 19:35 UTC, arthurkulchenko commented on app/models/user.rb
> +  class << self
вот выдает если сделать их приватными инстанс методами - NameError (undefined local variable or method `token_and_password_generating' for #<Class:0x007fc9e2ad34d8>):

2016-10-04 21:49 UTC, arthurkulchenko commented on app/models/user.rb
> +      token_and_password_generating
в методе класса self.token_and_password_generating поскольку token_and_password_generating - метод класса

2016-10-05 12:22 UTC, vkurennov commented on app/models/user.rb
> +    if authorization
Ровно так, как я выше написал: делаешь `return authorization.user if authorization`, т.е. если юзера нашли, то все, метод завершен. Весь остальной код будет выполняться только юзера не нашли. Т.е. это как бы else, но без else.

2016-10-05 12:29 UTC, vkurennov approved these changes
Принято, но измени метод find_for_ouath, как я написал и разберись с тем, как он написан

2016-10-05 12:29 UTC, vkurennov commented on app/models/user.rb
> +  class << self
А, точно, я забыл, что find_for_oauth - это метод класса. Ок, пусть остается

2016-10-05 12:29 UTC, vkurennov commented on app/models/user.rb
> +  def merge_this(user)
Да, логика в этом есть.

2016-10-05 12:29 UTC, vkurennov commented on app/models/user.rb
> +  def self.find_for_oauth(req)
Вот как надо избавиться от спагетти-кода:
```

 def self.find_for_oauth(req)
   authorization = Authorization.where(provider: req.provider, uid: req.uid.to_s).first
   return authorization.user if authorization
   
   # эта часть метода будет выполнятсья только если условие строкой выше не выполнится, ведь там return
   if req.info.has_key?(:email) && user = User.find_by(email: req.info[:email])
     user
   else
     password_generating
     email_genarating(req)
     user = User.create!(email: @g_email, password: @password, password_confirmation: @password, email_real: @r_email )
   end

   if user.authorizations.empty?
     user.authorizations.create!(provider: req.provider, uid: req.uid.to_s)
   end
   
   user
 end
```

 

2016-10-05 13:00 UTC, arthurkulchenko commented on app/models/user.rb
> +  def self.find_for_oauth(req)
да уже позже допетрил после прочтения комментария)

2016-10-06 10:14 UTC, merged