add cancancan abilities
arthurkulchenko/qna_think pull request #14
Opened 2016-10-06 13:15 UTC by arthurkulchenko

2016-10-06 17:22 UTC, vkurennov requested changes
Исправь замечания и во вьюхах замени проверки с наших методов на can?

2016-10-06 17:22 UTC, vkurennov commented on app/controllers/application_controller.rb
> +    redirect_to root_path, alert: exception.message
Это сработает только для html-запросов и не для ajax, т.к. для ajax редирект будет в фоне. 
Сделай проддержку json и js: 

 - для json вовзращаем текст сообщения и статус :forbidden, и вешаем на клиенте голобальный обработчик этой ошибки. 
 - для js пусть ренедерится вьюха, которая отобразит на странице сообщение и тоже статус :forbidden возвращается.

2016-10-06 17:22 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +  authorize_resource
Можно написать `authorize_resource except: :index`

2016-10-06 17:22 UTC, vkurennov commented on app/models/ability.rb
> +  def user_ability
Не маловато прав? На удаление? А аттачменты, например? Ну и для голосования правила сложнее. Ведь у нас создать голос может только не-автор вопроса/ответа, а удалить голос может только тот, кто его создал.

2016-10-06 17:22 UTC, vkurennov commented on app/models/ability.rb
> +  def user_ability
Внимательнее проанализируй все права пользователей

2016-10-10 10:35 UTC, arthurkulchenko commented on app/controllers/questions_controller.rb
> +  authorize_resource
не, тогда ошибку выдает.

2016-10-10 13:54 UTC, vkurennov approved these changes
Принято, но учти замечание

2016-10-10 13:54 UTC, vkurennov commented on app/models/ability.rb
> +    can :destroy, Vote, user: user
Используй сравнение по user_id: `user_id: user.id`, чтобы не делать лишний запрос в базу.

2016-10-10 15:38 UTC, merged