Rest api part 2
arthurkulchenko/qna_think pull request #16
Opened 2016-10-21 13:22 UTC by arthurkulchenko

With action cable realization

2016-11-04 10:41 UTC, vkurennov requested changes
Исправь замечания. И почему у тебя 10-е задание в этом же PR? Дико неудобно проверять. Каждое задание должно быть в своей ветке и в своем PR.

2016-11-04 10:41 UTC, vkurennov commented on app/controllers/api/v1/answers_controller.rb
> +                 )
Что за отступы странные? У respond_with можно скобки опустить, уже будет учше, а то как-то не очень смотрится, не по-рубишному :-)

2016-11-04 10:41 UTC, vkurennov commented on app/controllers/api/v1/answers_controller.rb
> +  load_and_authorize_resource except: [:create]
Вот тут проблема. CanCan использует current_user для создания инстанса класса Ability, а у нас этот метод в API всегда nil возращает (сесси-то нет), т.е. Ability у нас всегда для гостя. Надо сделать так, чтобы Ability создавалась с current_resource_owner

2016-11-04 10:41 UTC, vkurennov commented on app/controllers/api/v1/base_controller.rb
> +  skip_authorization_check
А почему тут skip_, если авторизацию мы все равно вызываем?

2016-11-04 10:41 UTC, vkurennov commented on app/controllers/api/v1/profiles_controller.rb
> +  skip_authorization_check
Тут skip_ не нужен, у тебя же внутри экшенов вызывается `authorize!`

2016-11-04 10:41 UTC, vkurennov commented on app/helpers/answer_helper.rb
> +  def user_authenticate_in?
Это что и зачем?

2016-11-04 10:41 UTC, vkurennov commented on app/helpers/answer_helper.rb
> +  def current_user_helper
Те же вопросы по поводу метода - зачем он?

2016-11-04 10:41 UTC, vkurennov commented on app/models/user.rb
> +  def admin?
Рельсы автоматом создают методы-предикаты для boolean-атрибутов, т.е. метод `admin?` уже и так есть

2016-11-04 10:41 UTC, vkurennov commented on app/models/question.rb
> +  validates_with Validators::QuestionValidator, fields: [:title, :content]
Это явное усложнение и размазывание логики. Кстомные валидаторы имеют смысл, если логика валидации сложная и/или если валидации переиспольуются в нескольких классах

2016-11-04 10:41 UTC, vkurennov commented on app/models/validators/question_validator.rb
> +class Validators::QuestionValidator < ActiveModel::Validator
Верни обычные валидации, ни к чему это усложнение

2016-11-04 10:41 UTC, vkurennov commented on spec/acceptance/answer/take_back_voice_spec.rb
> +#   scenario 'not owner of vote do not see link' do
А чего у тебя все тесты закоментарены?

2016-11-08 15:54 UTC, arthurkulchenko commented
Просто я слишко рано удалил старые ветки... и не знал куда эти комиты впихнуть

2016-11-08 16:10 UTC, arthurkulchenko commented on app/helpers/answer_helper.rb
> +  def user_authenticate_in?
это я пытался... неважно)))

2016-11-08 16:13 UTC, arthurkulchenko commented on app/models/question.rb
> +  validates_with Validators::QuestionValidator, fields: [:title, :content]
Это сделано для оформления, так как при алерте из js спец. сиволы приобретают вид hex

2016-11-08 16:40 UTC, arthurkulchenko commented on app/controllers/api/v1/answers_controller.rb
> +                 )
отступы до объекта к которому применяется метод

2016-11-08 16:42 UTC, arthurkulchenko commented on app/controllers/api/v1/answers_controller.rb
> +  load_and_authorize_resource except: [:create]
а как это сделать?

2016-11-09 08:02 UTC, arthurkulchenko commented on spec/acceptance/answer/take_back_voice_spec.rb
> +#   scenario 'not owner of vote do not see link' do
Пропала необходимость в этих тестах

2016-11-09 16:57 UTC, vkurennov requested changes
Ну на второй трети курса допускать такое элементарное дублирование - это не есть гуд.

2016-11-09 16:57 UTC, vkurennov commented on app/controllers/api/v1/answers_controller.rb
> +    @current_ability ||= Ability.new(current_resource_owner)
Верно, но ведь это используется при вызове каждого метода. Сделай еще один шаг, определи метод current_ability ровно с таким содержанием и вынести его в базовый котнролер для API

2016-11-09 16:57 UTC, vkurennov commented on app/controllers/api/v1/base_controller.rb
> +    @current_ability ||= Ability.new(current_user)
Можно и так, но лучше переопределить метод current_ability, именно его вызывает cancan и его методы в контроллерах

2016-11-09 16:57 UTC, vkurennov commented on app/controllers/api/v1/questions_controller.rb
> +    @current_ability ||= Ability.new(current_resource_owner)
а тут еще и дублирование. не смущает, что уже 3-й раз одну и ту же строчкку написал? А если бы контроллеров и экшенов было бы больше, то копировал бы каждый раз?

2016-11-09 19:35 UTC, arthurkulchenko commented
Да забыл убрать...

2016-11-10 12:31 UTC, vkurennov approved these changes

2016-11-10 20:07 UTC, merged